make deb uses tar.gz

diff --git a/bin/builddeb b/bin/builddeb
--- a/bin/builddeb
+++ b/bin/builddeb
@@ -6,7 +6,11 @@
 set -e
 
 CUR_DIR=`pwd`
-LOCALPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
+MY_PATH=$(cd ${0%/*} && echo $PWD/${0##*/})
+BIN_PATH=`dirname "$MY_PATH"`
+EZPAARSE_PATH=$BIN_PATH/..
+
+. $BIN_PATH/env
 
 # must be root to generate the package
 if [ "`id -u`" != 0 ]; then
@@ -14,34 +18,40 @@ if [ "`id -u`" != 0 ]; then
   exit 1
 fi
 
+[ -z "$VERSION" ] && VERSION="`$BIN_PATH/readconfig -k version`"
+if [ ! -f $EZPAARSE_PATH/ezpaarse-$VERSION/ezpaarse-${VERSION}.tar.gz ]; then
+  echo "Error: $EZPAARSE_PATH/ezpaarse-$VERSION/ezpaarse-${VERSION}.tar.gz  does not exist. Please run 'make zip' before."
+  exit 1
+fi
 
 rm -rf /tmp/ezpaarse/
-
 mkdir -p /tmp/ezpaarse/usr/share/
 
 # todo: remplacer par l'utilisation d'un tar.gz versionné (make release)
-cp -r $LOCALPATH /tmp/ezpaarse/usr/share/ezpaarse
+cd /tmp/ezpaarse/usr/share/
+tar xzf $EZPAARSE_PATH/ezpaarse-$VERSION/ezpaarse-${VERSION}.tar.gz 
+mv /tmp/ezpaarse/usr/share/ezpaarse-$VERSION/ /tmp/ezpaarse/usr/share/ezpaarse/
 cd /tmp/ezpaarse/
 
 # prepare folders structure
-cp -r $LOCALPATH/misc/deb/* /tmp/ezpaarse/
+cp -r $EZPAARSE_PATH/misc/deb/* /tmp/ezpaarse/
 
 # cleanup
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/logs/
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/.git/
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/test/
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/build/
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/misc/
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/platforms/*/test/
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/*.deb
-rm -rf /tmp/ezpaarse/usr/share/ezpaarse/*.rpm
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "tests"     -type d -exec rm -rf {} \; 2>/dev/null || true
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "test"      -type d -exec rm -rf {} \; 2>/dev/null || true
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "dist"      -type d -exec rm -rf {} \; 2>/dev/null || true
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "build"     -type d -exec rm -rf {} \; 2>/dev/null || true
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "example"   -type d -exec rm -rf {} \; 2>/dev/null || true
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "examples"  -type d -exec rm -rf {} \; 2>/dev/null || true
-find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "benchmark" -type d -exec rm -rf {} \; 2>/dev/null || true
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/logs/
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/.git/
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/test/
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/build/
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/misc/
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/platforms/*/test/
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/*.deb
+#rm -rf /tmp/ezpaarse/usr/share/ezpaarse/*.rpm
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "tests"     -type d -exec rm -rf {} \; 2>/dev/null || true
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "test"      -type d -exec rm -rf {} \; 2>/dev/null || true
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "dist"      -type d -exec rm -rf {} \; 2>/dev/null || true
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "build"     -type d -exec rm -rf {} \; 2>/dev/null || true
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "example"   -type d -exec rm -rf {} \; 2>/dev/null || true
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "examples"  -type d -exec rm -rf {} \; 2>/dev/null || true
+#find /tmp/ezpaarse/usr/share/ezpaarse/node_modules/ -name "benchmark" -type d -exec rm -rf {} \; 2>/dev/null || true
 
 # LSBization of ezpaarse source code
 
@@ -69,9 +79,9 @@ PACKAGE=`dpkg-deb -f $NAME.deb package`
 VERSION=`dpkg-deb -f $NAME.deb version`
 ARCHI=`dpkg-deb -f $NAME.deb architecture`
 NAMENEW="${PACKAGE}-${VERSION}_${ARCHI}"
-mv $NAME.deb $CUR_DIR/${NAMENEW}.deb
+mv $NAME.deb $CUR_DIR/ezpaarse-$VERSION/${NAMENEW}.deb
 
-echo "ezpaarse debian package built: $CUR_DIR/${NAMENEW}.deb"
+echo "ezpaarse debian package built: $CUR_DIR/ezpaarse-$VERSION/${NAMENEW}.deb"
 cd $CUR_DIR
 
 rm -rf /tmp/ezpaarse/
