add a lockfile while updating

diff --git a/bin/update-app b/bin/update-app
--- a/bin/update-app
+++ b/bin/update-app
@@ -1,27 +1,37 @@
 #!/bin/bash
 #
 # Stop ezPAARSE, update the core and restart
-# Options: [--latest][-l]   Update to the bleeding edge instead of the latest tag
+# Options: [--latest][-l]   Update to the bleeding edge of the current branch instead of the latest tag
+#                           If in detached state, switch to master
 #          [--rebuild][-b]  Call 'make' once updated
 #          [--force][-f]    Overwrite any existing change in the working tree (use it carefully)
 #
-# Status flags :  [1] Failed to stop
-#                 [2] Failed to update
-#                 [4] Failed to rebuild
-#                 [8] Failed to restart
+# Status flags :  [1]  Another instance of the script is already running
+#                 [2]  Failed to stop ezPAARSE
+#                 [4]  Failed to update the core
+#                 [8]  Failed to rebuild
+#                 [16] Failed to restart ezPAARSE
 #
 # Status code is a bitwise flags enumeration
-# [failed to update] + [failed to restart] = 2|8 = 10
+# [failed to update] + [failed to restart] = 4|16 = 20
 #
-# [10 & 8 == 8] => [failed to restart]
-# [10 & 4 != 4] => [No rebuild or rebuild successful]
+# [20 & 16 == 16] => [failed to restart]
+#   [20 & 4 != 4] => [No rebuild or rebuild successful]
+
+STATUS=0
 
 cd "$( dirname "${BASH_SOURCE[0]}" )/.."
+
+if ( set -o noclobber; echo "$$" > update.lock) 2> /dev/null ; then
+  trap 'rm -f update.lock; exit $STATUS' INT TERM EXIT
+else
+  echo "Another instance is already running"
+  exit 16
+fi
 
 LATEST=false
 REBUILD=false
 FORCE=""
-STATUS=0
 
 for i in "$@"
 do
@@ -50,7 +60,7 @@ if [[ $CURRENT_BRANCH == 'HEAD' ]]; then
 fi
 
 make stop
-if [[ $? -gt 0 ]]; then STATUS=1; fi
+if [[ $? -gt 0 ]]; then STATUS=2; fi
 
 if [[ $STATUS -eq 0 ]]; then
   if [[ $LATEST == true ]]; then
@@ -63,15 +73,15 @@ if [[ $STATUS -eq 0 ]]; then
     git checkout $LATEST_TAG $FORCE
   fi
 
-  if [[ $? -gt 0 ]]; then STATUS=2; fi
+  if [[ $? -gt 0 ]]; then STATUS=4; fi
 
   if [[ $STATUS -eq 0 && $REBUILD == true ]]; then
     make
-    if [[ $? -gt 0 ]]; then STATUS=4; fi
+    if [[ $? -gt 0 ]]; then STATUS=8; fi
   fi
 fi
 
 make start
 
-if [[ $? -gt 0 ]]; then STATUS=$(($STATUS | 8)); fi
+if [[ $? -gt 0 ]]; then STATUS=$(($STATUS | 16)); fi
 exit $STATUS
